// <auto-generated />
using System;
using GroupsScoreSheet.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GroupsScoreSheet.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GroupsScoreSheet.Api.Domain.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActiveRoundId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoldingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrganizerCompanyName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ActiveRoundId");

                    b.ToTable("Courses", (string)null);
                });

            modelBuilder.Entity("GroupsScoreSheet.Api.Domain.Entities.CourseEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "Name")
                        .IsUnique();

                    b.ToTable("CourseEvents", (string)null);
                });

            modelBuilder.Entity("GroupsScoreSheet.Api.Domain.Entities.CourseTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "Name")
                        .IsUnique();

                    b.ToTable("CourseTeams", (string)null);
                });

            modelBuilder.Entity("GroupsScoreSheet.Api.Domain.Entities.EvaluationRound", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResetReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "RoundNumber")
                        .IsUnique();

                    b.HasIndex("CourseId", "Status")
                        .IsUnique()
                        .HasFilter("[Status] = 1");

                    b.ToTable("EvaluationRounds", (string)null);
                });

            modelBuilder.Entity("GroupsScoreSheet.Api.Domain.Entities.EvaluatorProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EvaluationRoundId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EvaluatorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EvaluatorToken")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("FinalSyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FirstOpenedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationRoundId");

                    b.HasIndex("EvaluatorToken")
                        .IsUnique();

                    b.HasIndex("CourseId", "EvaluationRoundId");

                    b.ToTable("EvaluatorProfiles", (string)null);
                });

            modelBuilder.Entity("GroupsScoreSheet.Api.Domain.Entities.EventComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ClientUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CommentText")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("CourseEventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EvaluationRoundId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EvaluatorProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourseEventId");

                    b.HasIndex("EvaluationRoundId");

                    b.HasIndex("TeamId");

                    b.HasIndex("CourseId", "EvaluationRoundId");

                    b.HasIndex("EvaluatorProfileId", "TeamId", "CourseEventId")
                        .IsUnique();

                    b.ToTable("EventComments", (string)null);
                });

            modelBuilder.Entity("GroupsScoreSheet.Api.Domain.Entities.EventIndicator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseEventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CourseEventId", "Name")
                        .IsUnique();

                    b.ToTable("EventIndicators", (string)null);
                });

            modelBuilder.Entity("GroupsScoreSheet.Api.Domain.Entities.Score", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ClientUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CourseEventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EvaluationRoundId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EvaluatorProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventIndicatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseEventId");

                    b.HasIndex("EvaluationRoundId");

                    b.HasIndex("EventIndicatorId");

                    b.HasIndex("TeamId");

                    b.HasIndex("CourseId", "EvaluationRoundId");

                    b.HasIndex("EvaluatorProfileId", "TeamId", "CourseEventId", "EventIndicatorId")
                        .IsUnique();

                    b.ToTable("Scores", null, t =>
                        {
                            t.HasCheckConstraint("CK_Scores_Value_0_10", "[Value] >= 0 AND [Value] <= 10");
                        });
                });

            modelBuilder.Entity("GroupsScoreSheet.Api.Domain.Entities.SyncLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("EvaluationRoundId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EvaluatorProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReceivedCommentsCount")
                        .HasColumnType("int");

                    b.Property<int>("ReceivedScoresCount")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SyncType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("EvaluationRoundId");

                    b.HasIndex("EvaluatorProfileId");

                    b.ToTable("SyncLogs", (string)null);
                });

            modelBuilder.Entity("GroupsScoreSheet.Api.Domain.Entities.UploadedExcelFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ImportStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ValidationSummary")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("UploadedExcelFiles", (string)null);
                });

            modelBuilder.Entity("GroupsScoreSheet.Api.Domain.Entities.Course", b =>
                {
                    b.HasOne("GroupsScoreSheet.Api.Domain.Entities.EvaluationRound", "ActiveRound")
                        .WithMany()
                        .HasForeignKey("ActiveRoundId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActiveRound");
                });

            modelBuilder.Entity("GroupsScoreSheet.Api.Domain.Entities.CourseEvent", b =>
                {
                    b.HasOne("GroupsScoreSheet.Api.Domain.Entities.Course", "Course")
                        .WithMany("Events")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("GroupsScoreSheet.Api.Domain.Entities.CourseTeam", b =>
                {
                    b.HasOne("GroupsScoreSheet.Api.Domain.Entities.Course", "Course")
                        .WithMany("Teams")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("GroupsScoreSheet.Api.Domain.Entities.EvaluationRound", b =>
                {
                    b.HasOne("GroupsScoreSheet.Api.Domain.Entities.Course", "Course")
                        .WithMany("Rounds")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("GroupsScoreSheet.Api.Domain.Entities.EvaluatorProfile", b =>
                {
                    b.HasOne("GroupsScoreSheet.Api.Domain.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GroupsScoreSheet.Api.Domain.Entities.EvaluationRound", "EvaluationRound")
                        .WithMany("EvaluatorProfiles")
                        .HasForeignKey("EvaluationRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("EvaluationRound");
                });

            modelBuilder.Entity("GroupsScoreSheet.Api.Domain.Entities.EventComment", b =>
                {
                    b.HasOne("GroupsScoreSheet.Api.Domain.Entities.CourseEvent", "CourseEvent")
                        .WithMany()
                        .HasForeignKey("CourseEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GroupsScoreSheet.Api.Domain.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GroupsScoreSheet.Api.Domain.Entities.EvaluationRound", "EvaluationRound")
                        .WithMany()
                        .HasForeignKey("EvaluationRoundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GroupsScoreSheet.Api.Domain.Entities.EvaluatorProfile", "EvaluatorProfile")
                        .WithMany("EventComments")
                        .HasForeignKey("EvaluatorProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupsScoreSheet.Api.Domain.Entities.CourseTeam", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("CourseEvent");

                    b.Navigation("EvaluationRound");

                    b.Navigation("EvaluatorProfile");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("GroupsScoreSheet.Api.Domain.Entities.EventIndicator", b =>
                {
                    b.HasOne("GroupsScoreSheet.Api.Domain.Entities.CourseEvent", "CourseEvent")
                        .WithMany("Indicators")
                        .HasForeignKey("CourseEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseEvent");
                });

            modelBuilder.Entity("GroupsScoreSheet.Api.Domain.Entities.Score", b =>
                {
                    b.HasOne("GroupsScoreSheet.Api.Domain.Entities.CourseEvent", "CourseEvent")
                        .WithMany()
                        .HasForeignKey("CourseEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GroupsScoreSheet.Api.Domain.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GroupsScoreSheet.Api.Domain.Entities.EvaluationRound", "EvaluationRound")
                        .WithMany()
                        .HasForeignKey("EvaluationRoundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GroupsScoreSheet.Api.Domain.Entities.EvaluatorProfile", "EvaluatorProfile")
                        .WithMany("Scores")
                        .HasForeignKey("EvaluatorProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupsScoreSheet.Api.Domain.Entities.EventIndicator", "EventIndicator")
                        .WithMany()
                        .HasForeignKey("EventIndicatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GroupsScoreSheet.Api.Domain.Entities.CourseTeam", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("CourseEvent");

                    b.Navigation("EvaluationRound");

                    b.Navigation("EvaluatorProfile");

                    b.Navigation("EventIndicator");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("GroupsScoreSheet.Api.Domain.Entities.SyncLog", b =>
                {
                    b.HasOne("GroupsScoreSheet.Api.Domain.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GroupsScoreSheet.Api.Domain.Entities.EvaluationRound", "EvaluationRound")
                        .WithMany()
                        .HasForeignKey("EvaluationRoundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GroupsScoreSheet.Api.Domain.Entities.EvaluatorProfile", "EvaluatorProfile")
                        .WithMany("SyncLogs")
                        .HasForeignKey("EvaluatorProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("EvaluationRound");

                    b.Navigation("EvaluatorProfile");
                });

            modelBuilder.Entity("GroupsScoreSheet.Api.Domain.Entities.UploadedExcelFile", b =>
                {
                    b.HasOne("GroupsScoreSheet.Api.Domain.Entities.Course", "Course")
                        .WithMany("UploadedExcelFiles")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("GroupsScoreSheet.Api.Domain.Entities.Course", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Rounds");

                    b.Navigation("Teams");

                    b.Navigation("UploadedExcelFiles");
                });

            modelBuilder.Entity("GroupsScoreSheet.Api.Domain.Entities.CourseEvent", b =>
                {
                    b.Navigation("Indicators");
                });

            modelBuilder.Entity("GroupsScoreSheet.Api.Domain.Entities.EvaluationRound", b =>
                {
                    b.Navigation("EvaluatorProfiles");
                });

            modelBuilder.Entity("GroupsScoreSheet.Api.Domain.Entities.EvaluatorProfile", b =>
                {
                    b.Navigation("EventComments");

                    b.Navigation("Scores");

                    b.Navigation("SyncLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
